# This file contains values from Cookiecutter

default_context:
  project_name: "pytest-fastapi-deps"
  project_description: "A fixture which allows easy replacement of fastapi dependencies for testing"
  organization: "Peter Kogan"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "pksol"
  email: "kogan.peter@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
